### ISSUE TITLE
Text on Landingpage is in foreign language

### ISSUE THREAD

**Issue by skatehouse** [goaround/affiliate-marker#1]
Hi, although I´ve selected german language the text on my starting-page is in english. 
Further i´m using affiliate banners or products and the star is on the left AND on the right of my picture. The text on these pages is in german - that´s okay.

**Comment by goaround** [comment]
Hi @skatehouse,

could you provide me a link to your starting page?

**Comment by skatehouse** [comment]
www.anzuziehen.de 
I like your plug-in and it would be also nice if I could manage to format the font settings.
Thanks for helping me out. 
I´ve changed all texts from english to german. Now issue has gone :-)

Look also at Datenschutzerklärung at the bottom ;-) There is no reason for the text underneath. 
On the starting page I have included some banners - that´s why the text is underneath. Maybe you could just tell how to fit it to the page or change the font or color. 
After that issue can be closed ;-)

**Comment by goaround** [comment]
Sorry for the late replay. There is now a settings page available where you can add your own domains/URL parts and change the disclosure.
There you can replace `amazon` with your Amazon PartnerNet tag e.g. `tag=traveldealz07-21` and the disclosure at the end of your _Datenschutzerklärung_ should be gone.

If you upgrade to the latest version, there is a CSS class applied to the disclosure `affiliate-marker-disclosure` You can change the font settings with some custom CSS e.g. `.affiliate-marker-disclosure { font-size: small; }`
