### ISSUE TITLE
Text also under "Datenschutzvereinbarung"

### ISSUE THREAD

**Issue by skatehouse** [goaround/affiliate-marker#2]
Text is also visible on unwanted pages like "Datenschutzvereinbarung". There are also links to amazon. These should be excluded.

**Comment by goaround** [comment]
Hi @skatehouse,

I don't want to exclude certain pages. I think a false positive is better than a false negative.

**Comment by goaround** [comment]
A hint for you: instead of `amazon` you can add your Amazon PartnerNet tag e.g. `tag=traveldealz07-21` to your domain list. Than only if the link contains your tag it will be marked.
